<?php

return [
	'weapons' => [
		['name' => 'stick', 'image' => 'stick.jpg', 'price' => 0, 'premium' => 0, 'weight' => 5, 'properties' => ['requires' => ['level:1']], 'damage' => [1, 2], 'critChance' => 0.01, 'speed' => -0.05, 'type' => 'melee'],
		['name' => 'foam-sword', 'image' => 'foam-sword.jpg', 'price' => 15, 'premium' => 0, 'weight' => 2, 'properties' => ['requires' => ['level:1']], 'damage' => [2, 4], 'critChance' => 0.02, 'speed' => -0.01, 'type' => 'melee'],
		['name' => 'staff', 'image' => 'staff.jpg', 'price' => 25, 'premium' => 0, 'weight' => 8, 'properties' => ['requires' => ['level:1']], 'damage' => [3, 5], 'critChance' => 0.02, 'speed' => -0.07, 'type' => 'melee'],
		['name' => 'water-gun', 'image' => 'water-gun.jpg', 'price' => 25, 'premium' => 0, 'weight' => 4, 'properties' => ['requires' => ['level:1']], 'damage' => [2, 5], 'critChance' => 0.01, 'speed' => +0.05, 'type' => 'ranged'],
		['name' => 'knife', 'image' => 'knife.jpg', 'price' => 50, 'premium' => 0, 'weight' => 5, 'properties' => ['requires' => ['level:1']], 'damage' => [5, 9], 'critChance' => 0.05, 'speed' => +0, 'type' => 'melee'],
		['name' => 'paralizator', 'image' => 'paralizator.jpg', 'price' => 500, 'premium' => 0, 'weight' => 6, 'properties' => ['requires' => ['level:1']], 'damage' => [8, 13], 'critChance' => 0.1, 'speed' => +0, 'type' => 'melee'],
		['name' => 'baseball-bat', 'image' => 'baseball-bat.jpg', 'price' => 200, 'premium' => 0, 'weight' => 15, 'properties' => ['requires' => ['level:5']], 'damage' => [10, 15], 'critChance' => 0.03, 'speed' => -0.09, 'type' => 'melee'],
		['name' => 'peper-spray', 'image' => 'peper-spray.jpg', 'price' => 150, 'premium' => 0, 'weight' => 8, 'properties' => ['requires' => ['level:5']], 'damage' => [5, 9], 'critChance' => 0.03, 'speed' => +0, 'type' => 'ranged'],
		['name' => 'knuckle-duster', 'image' => 'knuckle-duster.jpg', 'price' => 75, 'premium' => 0, 'weight' => 5, 'properties' => ['requires' => ['level:5']], 'damage' => [4, 7], 'critChance' => 0.02, 'speed' => +0, 'type' => 'melee'],
		['name' => 'machete', 'image' => 'machete.jpg', 'price' => 250, 'premium' => 0, 'weight' => 25, 'properties' => ['requires' => ['level:5']], 'damage' => [13, 18], 'critChance' => 0.07, 'speed' => +0.02, 'type' => 'melee'],
		['name' => 'sword', 'image' => 'sword.jpg', 'price' => 750, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:10']], 'damage' => [15, 20], 'critChance' => 0.1, 'speed' => +0.04, 'type' => 'melee'],
		['name' => 'colt-1911', 'image' => 'colt-1911.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:10']], 'damage' => [20, 25], 'critChance' => 0.1, 'speed' => +0.06, 'type' => 'ranged'],
		['name' => 'glock', 'image' => 'glock.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:10']], 'damage' => [20, 25], 'critChance' => 0.1, 'speed' => +0.06, 'type' => 'ranged'],
		['name' => 'ak-47', 'image' => 'ak-47.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:25']], 'damage' => [20, 25], 'critChance' => 0.1, 'speed' => +0.06, 'type' => 'ranged'],
		['name' => 'm4a1', 'image' => 'm4a1.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:25']], 'damage' => [20, 25], 'critChance' => 0.1, 'speed' => +0.06, 'type' => 'ranged'],
		['name' => 'flare', 'image' => 'flare.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:25']], 'damage' => [20, 25], 'critChance' => 0.1, 'speed' => +0.06, 'type' => 'ranged'],
		['name' => 'bazooka', 'image' => 'bazooka.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:25']], 'damage' => [20, 25], 'critChance' => 0.1, 'speed' => +0.06, 'type' => 'ranged'],
	],
	'armors' => [
		['name' => 't-shirt', 'image' => 't-shirt.jpg', 'price' => 25, 'premium' => 0, 'weight' => 2, 'properties' => ['requires' => ['level:1']], 'armor' => 1, 'speed' => +0],
		['name' => 'pan-colander', 'image' => 'pan-colander.jpg', 'price' => 50, 'premium' => 0, 'weight' => 8, 'properties' => ['requires' => ['level:5']], 'armor' => 3, 'speed' => -0.2],
		['name' => 'sumo-costume', 'image' => 'sumo-costume.jpg', 'price' => 30, 'premium' => 0, 'weight' => 6, 'properties' => ['requires' => ['level:5']], 'armor' => 5, 'speed' => -0.5],
		['name' => 'squire-armor', 'image' => 'squire-armor.jpg', 'price' => 100, 'premium' => 0, 'weight' => 9, 'properties' => ['requires' => ['level:10']], 'armor' => 7, 'speed' => -0.6],
		['name' => 'bulletprof-vest', 'image' => 'bulletprof-vest.jpg', 'price' => 500, 'premium' => 0, 'weight' => 13, 'properties' => ['requires' => ['level:10']], 'armor' => 10, 'speed' => -0.6],
		['name' => 'knight-armor', 'image' => 'knight-armor.jpg', 'price' => 1000, 'premium' => 0, 'weight' => 25, 'properties' => ['requires' => ['level:25']], 'armor' => 13, 'speed' => -0.8],
		['name' => 'kevlar', 'image' => 'kevlar.jpg', 'price' => 2000, 'premium' => 0, 'weight' => 15, 'properties' => ['requires' => ['level:25']], 'armor' => 15, 'speed' => -0.5],
		['name' => 'samurai-armor', 'image' => 'samurai-armor.jpg', 'price' => 5000, 'premium' => 0, 'weight' => 35, 'properties' => ['requires' => ['level:25']], 'armor' => 17, 'speed' => -0.4],
	],
	'foods' => [
		['name' => 'loaf', 'image' => 'loaf.jpg', 'price' => 5, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'health' => 1, 'energy' => null],
		['name' => 'doughnut', 'image' => 'doughnut.jpg', 'price' => 10, 'premium' => 0, 'weight' => 2, 'properties' => ['requires' => []], 'health' => 3, 'energy' => null],
		['name' => 'dinner', 'image' => 'dinner.jpg', 'price' => 15, 'premium' => 0, 'weight' => 3, 'properties' => ['requires' => []], 'health' => 5, 'energy' => null],
		['name' => 'kebab', 'image' => 'kebab.jpg', 'price' => 20, 'premium' => 0, 'weight' => 4, 'properties' => ['requires' => []], 'health' => 7, 'energy' => null],
		['name' => 'pizza', 'image' => 'pizza.jpg', 'price' => 25, 'premium' => 0, 'weight' => 5, 'properties' => ['requires' => []], 'health' => 10, 'energy' => null],
		['name' => 'water', 'image' => 'water.jpg', 'price' => 5, 'premium' => 0, 'weight' => 3, 'properties' => ['requires' => []], 'health' => null, 'energy' => 1],
		['name' => 'juice', 'image' => 'juice.jpg', 'price' => 10, 'premium' => 0, 'weight' => 3, 'properties' => ['requires' => []], 'health' => null, 'energy' => 3],
		['name' => 'tea', 'image' => 'tea.jpg', 'price' => 15, 'premium' => 0, 'weight' => 3, 'properties' => ['requires' => []], 'health' => null, 'energy' => 5],
		['name' => 'coffee', 'image' => 'coffee.jpg', 'price' => 20, 'premium' => 0, 'weight' => 3, 'properties' => ['requires' => []], 'health' => null, 'energy' => 7],
		['name' => 'energy-drink', 'image' => 'energy-drink.jpg', 'price' => 25, 'premium' => 0, 'weight' => 3, 'properties' => ['requires' => []], 'health' => null, 'energy' => 10],
	],
	'seeds' => [
		['name' => 'critical-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:1']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [50, 100], 'quality' => [0.13, 0.17]],
		['name' => 'shaman-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:5']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [75, 100], 'quality' => [0.11, 0.15]],
		['name' => 'grapefruit-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:10']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [50, 125], 'quality' => [0.09, 0.25]],
		['name' => 'kush-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:10']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [50, 100], 'quality' => [0.13, 0.17]],
		['name' => 'passion-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:15']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [50, 100], 'quality' => [0.13, 0.17]],
		['name' => 'maroc-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:15']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [50, 100], 'quality' => [0.13, 0.17]],
		['name' => 'skunk-seed', 'image' => 'seed.jpg', 'price' => 20, 'premium' => 0, 'weight' => 0.1, 'properties' => ['requires' => ['level:15']], 'growth' => 1970, 'watering' => 1970, 'harvest' => [50, 100], 'quality' => [0.13, 0.17]],
	],
	'stuffs' => [
		['name' => 'critical-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.15],
		['name' => 'shaman-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.13],
		['name' => 'grapefruit-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.17],
		['name' => 'kush-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.15],
		['name' => 'passion-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.15],
		['name' => 'maroc-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.15],
		['name' => 'skunk-stuff', 'image' => 'stuff.jpg', 'price' => 10, 'premium' => 0, 'weight' => 1, 'properties' => ['requires' => []], 'quality' => 0.15],
	],
	'vehicles' => [
		['name' => 'bicycle', 'image' => 'bicycle.jpg', 'price' => 100, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 12.5, 'cost' => 0, 'capacity' => 0, 'boostable' => 0],
		['name' => 'scooter', 'image' => 'scooter.jpg', 'price' => 500, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 16.5, 'cost' => 1, 'capacity' => 100, 'boostable' => 1],
		['name' => 'quad', 'image' => 'quad.jpg', 'price' => 1500, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 18, 'cost' => 1, 'capacity' => 150, 'boostable' => 1],
		['name' => 'cross', 'image' => 'cross.jpg', 'price' => 3000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 16.5, 'cost' => 1, 'capacity' => 250, 'boostable' => 1],
		['name' => 'motor', 'image' => 'motor.jpg', 'price' => 10000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 21, 'cost' => 2, 'capacity' => 250, 'boostable' => 1],
		['name' => 'city-car', 'image' => 'city-car.jpg', 'price' => 25000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 22.5, 'cost' => 2.5, 'capacity' => 500, 'boostable' => 1],
		['name' => 'chaser', 'image' => 'chaser.jpg', 'price' => 25000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 25, 'cost' => 5, 'capacity' => 250, 'boostable' => 1],
		['name' => 'racing-car', 'image' => 'racing-car.jpg', 'price' => 100000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 25, 'cost' => 4, 'capacity' => 500, 'boostable' => 1],
		['name' => 'limousine', 'image' => 'limousine.jpg', 'price' => 1000000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 25, 'cost' => 3, 'capacity' => 750, 'boostable' => 1],
		['name' => 'helicopter', 'image' => 'helicopter.jpg', 'price' => 5000000, 'premium' => 0, 'weight' => 100, 'properties' => ['requires' => []], 'speed' => 250, 'cost' => 100, 'capacity' => 75, 'boostable' => 1],
	],
];
?>