<?php

return [
	'weapons' => [
		[
			'name' => 'foam-sword',
			'image' => 'foam-sword.jpg',
			'price' => 50,
			'weight' => 2,
			'premium' => 0,
			'properties' => ['requires' => ['strength:1']],
			'damage' => [1, 2],
			'critChance' => 0.01,
			'speed' => +0,
			'type' => 'melee',
		],
		[
			'name' => 'water-gun',
			'image' => 'water-gun.jpg',
			'price' => 70,
			'weight' => 2,
			'premium' => 0,
			'properties' => ['requires' => ['perception:1']],
			'damage' => [2, 3],
			'critChance' => 0.01,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'stick',
			'image' => 'stick.jpg',
			'price' => 40,
			'weight' => 2,
			'premium' => 0,
			'properties' => ['requires' => ['strength:3']],
			'damage' => [3, 4],
			'critChance' => 0.01,
			'speed' => +0,
			'type' => 'melee',
		],
		[
			'name' => 'pop-gun',
			'image' => 'pop-gun.jpg',
			'price' => 100,
			'weight' => 2,
			'premium' => 0,
			'properties' => ['requires' => ['perception:3']],
			'damage' => [4, 5],
			'critChance' => 0.01,
			'speed' => +0.05,
			'type' => 'ranged',
		],
		[
			'name' => 'staff',
			'image' => 'staff.jpg',
			'price' => 160,
			'weight' => 5,
			'premium' => 0,
			'properties' => ['requires' => ['strength:5']],
			'damage' => [5, 6],
			'critChance' => 0.02,
			'speed' => +0,
			'type' => 'melee',
		],
		[
			'name' => 'penknife',
			'image' => 'penknife.jpg',
			'price' => 200,
			'weight' => 3,
			'premium' => 0,
			'properties' => ['requires' => ['strength:2', 'agility:4']],
			'damage' => [6, 7],
			'critChance' => 0.05,
			'speed' => +0.1,
			'type' => 'melee',
		],
		[
			'name' => 'pepper-spray',
			'image' => 'pepper-spray.jpg',
			'price' => 350,
			'weight' => 2,
			'premium' => 0,
			'properties' => ['requires' => ['perception:4']],
			'damage' => [7, 8],
			'critChance' => 0.06,
			'speed' => +0.05,
			'type' => 'ranged',
		],
		[
			'name' => 'baseball-bat',
			'image' => 'baseball-bat.jpg',
			'price' => 300,
			'weight' => 5,
			'premium' => 0,
			'properties' => ['requires' => ['strength:8', 'endurance:4']],
			'damage' => [8, 9],
			'critChance' => 0.08,
			'speed' => +0,
			'type' => 'melee',
		],
		[
			'name' => 'dagger',
			'image' => 'dagger.jpg',
			'price' => 500,
			'weight' => 3,
			'premium' => 0,
			'properties' => ['requires' => ['strength:5', 'agility:10']],
			'damage' => [9, 10],
			'critChance' => 0.15,
			'speed' => +0.1,
			'type' => 'melee',
		],
		[
			'name' => 'flintlock',
			'image' => 'flintlock.jpg',
			'price' => 720,
			'weight' => 4,
			'premium' => 0,
			'properties' => ['requires' => ['strength:4', 'perception:7']],
			'damage' => [10, 11],
			'critChance' => 0.02,
			'speed' => -0.05,
			'type' => 'ranged',
		],
		[
			'name' => 'hunting-knife',
			'image' => 'hunting-knife.jpg',
			'price' => 924,
			'weight' => 3,
			'premium' => 0,
			'properties' => ['requires' => ['strength:3', 'agility:10']],
			'damage' => [11, 12],
			'critChance' => 0.01,
			'speed' => +0.2,
			'type' => 'melee',
		],
		[
			'name' => 'shuriken',
			'image' => 'shuriken.jpg',
			'price' => 1220,
			'weight' => 3,
			'premium' => 0,
			'properties' => ['requires' => ['perception:10', 'agility:7']],
			'damage' => [12, 13],
			'critChance' => 0.15,
			'speed' => +0.05,
			'type' => 'ranged',
		],
		[
			'name' => 'battle-staff',
			'image' => 'battle-staff.jpg',
			'price' => 1659,
			'weight' => 6,
			'premium' => 0,
			'properties' => ['requires' => ['strength:12', 'endurance:4']],
			'damage' => [13, 16],
			'critChance' => 0.06,
			'speed' => +0,
			'type' => 'melee',
		],
		[
			'name' => 'tomahawk',
			'image' => 'tomahawk.jpg',
			'price' => 2439,
			'weight' => 4,
			'premium' => 0,
			'properties' => ['requires' => ['strength:3', 'perception:13', 'agility:8']],
			'damage' => [14, 18],
			'critChance' => 0.09,
			'speed' => +0.05,
			'type' => 'ranged',
		],
		[
			'name' => 'hatchet',
			'image' => 'hatchet.jpg',
			'price' => 3171,
			'weight' => 9,
			'premium' => 0,
			'properties' => ['requires' => ['strength:15', 'endurance:6']],
			'damage' => [15, 20],
			'critChance' => 0.18,
			'speed' => -0.05,
			'type' => 'melee',
		],
		[
			'name' => 'machete',
			'image' => 'machete.jpg',
			'price' => 4281,
			'weight' => 8,
			'premium' => 0,
			'properties' => ['requires' => ['strength:20', 'agility:8']],
			'damage' => [16, 21],
			'critChance' => 0.18,
			'speed' => +0,
			'type' => 'melee',
		],
		[
			'name' => 'musket',
			'image' => 'musket.jpg',
			'price' => 6293,
			'weight' => 7,
			'premium' => 0,
			'properties' => ['requires' => ['strength:8', 'perception:17']],
			'damage' => [17, 22],
			'critChance' => 0.08,
			'speed' => -0.1,
			'type' => 'ranged',
		],
		[
			'name' => 'taser',
			'image' => 'taser.jpg',
			'price' => 8495,
			'weight' => 3,
			'premium' => 0,
			'properties' => ['requires' => ['strength:6', 'agility:6', 'intelligence:12']],
			'damage' => [18, 27],
			'critChance' => 0.09,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'assault-knife',
			'image' => 'assault-knife.jpg',
			'price' => 11468,
			'weight' => 4,
			'premium' => 0,
			'properties' => ['requires' => ['strength:8', 'agility:20']],
			'damage' => [19, 32],
			'critChance' => 0.06,
			'speed' => +0.15,
			'type' => 'melee',
		],
		[
			'name' => 'pistol',
			'image' => 'pistol.jpg',
			'price' => 15253,
			'weight' => 6,
			'premium' => 0,
			'properties' => ['requires' => ['strength:4', 'perception:20', 'agility:6']],
			'damage' => [22, 35],
			'critChance' => 0.15,
			'speed' => +0.1,
			'type' => 'ranged',
		],
		[
			'name' => 'axe',
			'image' => 'axe.jpg',
			'price' => 19828,
			'weight' => 15,
			'premium' => 0,
			'properties' => ['requires' => ['strength:25', 'endurance:10']],
			'damage' => [25, 40],
			'critChance' => 0.2,
			'speed' => -0.1,
			'type' => 'melee',
		],
		[
			'name' => 'pistol-silencer',
			'image' => 'pistol-silencer.jpg',
			'price' => 25975,
			'weight' => 8,
			'premium' => 0,
			'properties' => ['requires' => ['strength:5', 'perception:25', 'agility:15']],
			'damage' => [29, 45],
			'critChance' => 0.12,
			'speed' => +0.1,
			'type' => 'ranged',
		],
		[
			'name' => 'revolver',
			'image' => 'revolver.jpg',
			'price' => 38184,
			'weight' => 7,
			'premium' => 0,
			'properties' => ['requires' => ['strength:10', 'perception:30', 'agility:15']],
			'damage' => [32, 50],
			'critChance' => 0.15,
			'speed' => +0.5,
			'type' => 'ranged',
		],
		[
			'name' => 'battle-gun',
			'image' => 'battle-gun.jpg',
			'price' => 51548,
			'weight' => 10,
			'premium' => 0,
			'properties' => ['requires' => ['strength:15', 'perception:30', 'agility:15']],
			'damage' => [37, 55],
			'critChance' => 0.06,
			'speed' => -0.15,
			'type' => 'ranged',
		],
		[
			'name' => 'anti-gun',
			'image' => 'anti-gun.jpg',
			'price' => 67012,
			'weight' => 13,
			'premium' => 0,
			'properties' => ['requires' => ['strength:25', 'perception:30', 'agility:15']],
			'damage' => [42, 60],
			'critChance' => 0.13,
			'speed' => -0.15,
			'type' => 'ranged',
		],
		[
			'name' => 'uzi',
			'image' => 'uzi.jpg',
			'price' => 89796,
			'weight' => 7,
			'premium' => 0,
			'properties' => ['requires' => ['strength:17', 'perception:35', 'agility:25']],
			'damage' => [47, 65],
			'critChance' => 0.15,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'saber',
			'image' => 'saber.jpg',
			'price' => 119429,
			'weight' => 8,
			'premium' => 0,
			'properties' => ['requires' => ['strength:30', 'agility:25', 'endurance:10']],
			'damage' => [52, 70],
			'critChance' => 0.1,
			'speed' => +0.15,
			'type' => 'melee',
		],
		[
			'name' => 'piston-rifle',
			'image' => 'piston-rifle.jpg',
			'price' => 162424,
			'weight' => 10,
			'premium' => 0,
			'properties' => ['requires' => ['strength:35', 'perception:30', 'endurance:20']],
			'damage' => [54, 75],
			'critChance' => 0.19,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'heavy-rifle',
			'image' => 'heavy-rifle.jpg',
			'price' => 217648,
			'weight' => 20,
			'premium' => 0,
			'properties' => ['requires' => ['strength:40', 'perception:35', 'endurance:25']],
			'damage' => [59, 80],
			'critChance' => 0.04,
			'speed' => -0.2,
			'type' => 'ranged',
		],
		[
			'name' => 'rifle',
			'image' => 'rifle.jpg',
			'price' => 282942,
			'weight' => 15,
			'premium' => 0,
			'properties' => ['requires' => ['strength:30', 'perception:50', 'agility:25']],
			'damage' => [64, 85],
			'critChance' => 0.11,
			'speed' => +0.1,
			'type' => 'ranged',
		],
		[
			'name' => 'katana',
			'image' => 'katana.jpg',
			'price' => 381972,
			'weight' => 10,
			'premium' => 0,
			'properties' => ['requires' => ['strength:25', 'agility:50']],
			'damage' => [69, 90],
			'critChance' => 0.11,
			'speed' => +0.25,
			'type' => 'melee',
		],
		[
			'name' => 'sawed',
			'image' => 'sawed.jpg',
			'price' => 504203,
			'weight' => 18,
			'premium' => 0,
			'properties' => ['requires' => ['strength:40', 'perception:40', 'endurance:20']],
			'damage' => [74, 95],
			'critChance' => 0.16,
			'speed' => -0.25,
			'type' => 'ranged',
		],
		[
			'name' => 'assault-smg',
			'image' => 'assault-smg.jpg',
			'price' => 660506,
			'weight' => 13,
			'premium' => 0,
			'properties' => ['requires' => ['strength:35', 'perception:50', 'agility:30']],
			'damage' => [79, 100],
			'critChance' => 0.05,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'assault-rifle',
			'image' => 'assault-rifle.jpg',
			'price' => 858658,
			'weight' => 15,
			'premium' => 0,
			'properties' => ['requires' => ['strength:35', 'perception:50', 'agility:45']],
			'damage' => [84, 105],
			'critChance' => 0.08,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'flamethrower',
			'image' => 'flamethrower.jpg',
			'price' => 1142016,
			'weight' => 25,
			'premium' => 0,
			'properties' => ['requires' => ['strength:50', 'endurance:40', 'intelligence:40']],
			'damage' => [89, 110],
			'critChance' => 0.18,
			'speed' => -0.15,
			'type' => 'ranged',
		],
		[
			'name' => 'machine-gun',
			'image' => 'machine-gun.jpg',
			'price' => 1530301,
			'weight' => 20,
			'premium' => 0,
			'properties' => ['requires' => ['strength:75', 'perception:50']],
			'damage' => [94, 115],
			'critChance' => 0.13,
			'speed' => +0.05,
			'type' => 'ranged',
		],
		[
			'name' => 'sniper-rifle',
			'image' => 'sniper-rifle.jpg',
			'price' => 2035300,
			'weight' => 17,
			'premium' => 0,
			'properties' => ['requires' => ['strength:60', 'perception:90', 'agility:75']],
			'damage' => [99, 120],
			'critChance' => 0.2,
			'speed' => -0.6,
			'type' => 'ranged',
		],
		[
			'name' => 'howitzer',
			'image' => 'howitzer.jpg',
			'price' => 2645890,
			'weight' => 10,
			'premium' => 0,
			'properties' => ['requires' => ['strength:80', 'endurance:60']],
			'damage' => [104, 125],
			'critChance' => 0.12,
			'speed' => +0,
			'type' => 'ranged',
		],
		[
			'name' => 'rocket-launcher',
			'image' => 'rocket-launcher.jpg',
			'price' => 3571952,
			'weight' => 35,
			'premium' => 0,
			'properties' => ['requires' => ['strength:70', 'endurance:50', 'intelligence:65']],
			'damage' => [109, 130],
			'critChance' => 0.12,
			'speed' => -0.75,
			'type' => 'ranged',
		],
		[
			'name' => 'minigun',
			'image' => 'minigun.jpg',
			'price' => 4822135,
			'weight' => 25,
			'premium' => 0,
			'properties' => ['requires' => ['strength:60', 'perception:100', 'endurance:50']],
			'damage' => [114, 135],
			'critChance' => 0.07,
			'speed' => +0.1,
			'type' => 'ranged',
		],
	],
	'foods' => [
		[
			'name' => 'water',
			'image' => 'water.jpg',
			'price' => 5,
			'weight' => 1,
			'premium' => 0,
			'properties' => [],
			'health' => null,
			'energy' => 1,
		],
		[
			'name' => 'juice',
			'image' => 'juice.jpg',
			'price' => 8,
			'weight' => 2,
			'premium' => 0,
			'properties' => [],
			'health' => null,
			'energy' => 3,
		],
		[
			'name' => 'tea',
			'image' => 'tea.jpg',
			'price' => 20,
			'weight' => 2,
			'premium' => 0,
			'properties' => [],
			'health' => null,
			'energy' => 5,
		],
		[
			'name' => 'coffee',
			'image' => 'coffee.jpg',
			'price' => 35,
			'weight' => 2,
			'premium' => 0,
			'properties' => [],
			'health' => null,
			'energy' => 10,
		],
		[
			'name' => 'energy-drink',
			'image' => 'energy-drink.jpg',
			'price' => 50,
			'weight' => 2,
			'premium' => 0,
			'properties' => [],
			'health' => null,
			'energy' => 25,
		],
		[
			'name' => 'cannabis-energy-drink',
			'image' => 'cannabis-energy-drink.jpg',
			'price' => 5,
			'weight' => 2,
			'premium' => 1,
			'properties' => [],
			'health' => null,
			'energy' => 100,
		],
	],
	'seeds' => [
		[
			'name' => 'auto-dwarf-seed',
			'image' => 'seed.png',
			'price' => 20,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:0']],
			'growth' => 360,
			'watering' => 180,
			'harvest' => [7, 10],
			'quality' => 2,
		],
		[
			'name' => 'auto-bubblegum-seed',
			'image' => 'seed.png',
			'price' => 27,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:5']],
			'growth' => 378,
			'watering' => 0,
			'harvest' => [8, 11],
			'quality' => 5,
		],
		[
			'name' => 'auto-blueberry-seed',
			'image' => 'seed.png',
			'price' => 38,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:9']],
			'growth' => 397,
			'watering' => 132,
			'harvest' => [8, 13],
			'quality' => 4,
		],
		[
			'name' => 'blueberry-seed',
			'image' => 'seed.png',
			'price' => 51,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:14']],
			'growth' => 13098,
			'watering' => 3,
			'harvest' => [143, 214],
			'quality' => 4,
		],
		[
			'name' => 'auto-passion-seed',
			'image' => 'seed.png',
			'price' => 70,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:18']],
			'growth' => 463,
			'watering' => 116,
			'harvest' => [11, 16],
			'quality' => 3,
		],
		[
			'name' => 'auto-big-bud-seed',
			'image' => 'seed.png',
			'price' => 98,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:23']],
			'growth' => 486,
			'watering' => 0,
			'harvest' => [12, 18],
			'quality' => 4,
		],
		[
			'name' => 'auto-big-devil-seed',
			'image' => 'seed.png',
			'price' => 126,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:27']],
			'growth' => 515,
			'watering' => 103,
			'harvest' => [14, 20],
			'quality' => 4,
		],
		[
			'name' => 'auto-big-devil-xl-seed',
			'image' => 'seed.png',
			'price' => 168,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:32']],
			'growth' => 546,
			'watering' => 0,
			'harvest' => [15, 23],
			'quality' => 4,
		],
		[
			'name' => 'auto-black-jack-seed',
			'image' => 'seed.png',
			'price' => 234,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:36']],
			'growth' => 584,
			'watering' => 97,
			'harvest' => [17, 25],
			'quality' => 4,
		],
		[
			'name' => 'auto-durban-poison-seed',
			'image' => 'seed.png',
			'price' => 334,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:41']],
			'growth' => 613,
			'watering' => 0,
			'harvest' => [19, 28],
			'quality' => 4,
		],
		[
			'name' => 'auto-cheese-seed',
			'image' => 'seed.png',
			'price' => 460,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:45']],
			'growth' => 644,
			'watering' => 92,
			'harvest' => [22, 32],
			'quality' => 4,
		],
		[
			'name' => 'auto-jack-herer-seed',
			'image' => 'seed.png',
			'price' => 660,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:50']],
			'growth' => 676,
			'watering' => 0,
			'harvest' => [25, 38],
			'quality' => 4,
		],
		[
			'name' => 'auto-critical-seed',
			'image' => 'seed.png',
			'price' => 932,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:55']],
			'growth' => 724,
			'watering' => 90,
			'harvest' => [29, 43],
			'quality' => 4,
		],
		[
			'name' => 'critical-seed',
			'image' => 'seed.png',
			'price' => 1415,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:59']],
			'growth' => 22794,
			'watering' => 8,
			'harvest' => [485, 727],
			'quality' => 4,
		],
		[
			'name' => 'auto-white-widow-seed',
			'image' => 'seed.png',
			'price' => 1933,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:64']],
			'growth' => 805,
			'watering' => 90,
			'harvest' => [37, 56],
			'quality' => 4,
		],
		[
			'name' => 'white-widow-seed',
			'image' => 'seed.png',
			'price' => 2752,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:68']],
			'growth' => 25370,
			'watering' => 9,
			'harvest' => [648, 972],
			'quality' => 4,
		],
		[
			'name' => 'auto-mazar-seed',
			'image' => 'seed.png',
			'price' => 3721,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:73']],
			'growth' => 888,
			'watering' => 89,
			'harvest' => [49, 74],
			'quality' => 4,
		],
		[
			'name' => 'mazar-seed',
			'image' => 'seed.png',
			'price' => 5217,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:77']],
			'growth' => 27971,
			'watering' => 10,
			'harvest' => [848, 1272],
			'quality' => 4,
		],
		[
			'name' => 'auto-ak-47-seed',
			'image' => 'seed.png',
			'price' => 7293,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:82']],
			'growth' => 979,
			'watering' => 89,
			'harvest' => [64, 96],
			'quality' => 4,
		],
		[
			'name' => 'ak-47-seed',
			'image' => 'seed.png',
			'price' => 9890,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:86']],
			'growth' => 31131,
			'watering' => 12,
			'harvest' => [1058, 1587],
			'quality' => 4,
		],
		[
			'name' => 'auto-amnesia-haze-seed',
			'image' => 'seed.png',
			'price' => 13588,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:91']],
			'growth' => 1090,
			'watering' => 84,
			'harvest' => [79, 118],
			'quality' => 4,
		],
		[
			'name' => 'amnesia-haze-seed',
			'image' => 'seed.png',
			'price' => 18861,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['plantator:95']],
			'growth' => 34322,
			'watering' => 14,
			'harvest' => [1273, 1909],
			'quality' => 4,
		],
	],
	'stuffs' => [
		[
			'name' => 'auto-dwarf-stuff',
			'image' => 'auto-dwarf.jpg',
			'price' => 3,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:0']],
			'quality' => 0,
		],
		[
			'name' => 'auto-bubblegum-stuff',
			'image' => 'auto-bubblegum.jpg',
			'price' => 4,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:5']],
			'quality' => 0,
		],
		[
			'name' => 'auto-blueberry-stuff',
			'image' => 'auto-blueberry.jpg',
			'price' => 5,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:9']],
			'quality' => 0,
		],
		[
			'name' => 'blueberry-stuff',
			'image' => 'blueberry.jpg',
			'price' => 6,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:14']],
			'quality' => 0,
		],
		[
			'name' => 'auto-passion-stuff',
			'image' => 'auto-passion.jpg',
			'price' => 8,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:18']],
			'quality' => 0,
		],
		[
			'name' => 'auto-big-bud-stuff',
			'image' => 'auto-big-bud.jpg',
			'price' => 11,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:23']],
			'quality' => 0,
		],
		[
			'name' => 'auto-big-devil-stuff',
			'image' => 'auto-big-devil.jpg',
			'price' => 14,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:27']],
			'quality' => 0,
		],
		[
			'name' => 'auto-big-devil-xl-stuff',
			'image' => 'auto-big-devil-xl.jpg',
			'price' => 19,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:32']],
			'quality' => 0,
		],
		[
			'name' => 'auto-black-jack-stuff',
			'image' => 'auto-black-jack.jpg',
			'price' => 24,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:36']],
			'quality' => 0,
		],
		[
			'name' => 'auto-durban-poison-stuff',
			'image' => 'auto-durban-poison.jpg',
			'price' => 30,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:41']],
			'quality' => 0,
		],
		[
			'name' => 'auto-cheese-stuff',
			'image' => 'auto-cheese.jpg',
			'price' => 40,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:45']],
			'quality' => 0,
		],
		[
			'name' => 'auto-jack-herer-stuff',
			'image' => 'auto-jack-herer.jpg',
			'price' => 51,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:50']],
			'quality' => 0,
		],
		[
			'name' => 'auto-critical-stuff',
			'image' => 'auto-critical.jpg',
			'price' => 67,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:55']],
			'quality' => 0,
		],
		[
			'name' => 'critical-stuff',
			'image' => 'critical.jpg',
			'price' => 87,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:59']],
			'quality' => 0,
		],
		[
			'name' => 'auto-white-widow-stuff',
			'image' => 'auto-white-widow.jpg',
			'price' => 113,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:64']],
			'quality' => 0,
		],
		[
			'name' => 'white-widow-stuff',
			'image' => 'white-widow.jpg',
			'price' => 151,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:68']],
			'quality' => 0,
		],
		[
			'name' => 'auto-mazar-stuff',
			'image' => 'auto-mazar.jpg',
			'price' => 196,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:73']],
			'quality' => 0,
		],
		[
			'name' => 'mazar-stuff',
			'image' => 'mazar.jpg',
			'price' => 242,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:77']],
			'quality' => 0,
		],
		[
			'name' => 'auto-ak-47-stuff',
			'image' => 'auto-ak-47.jpg',
			'price' => 319,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:82']],
			'quality' => 0,
		],
		[
			'name' => 'ak-47-stuff',
			'image' => 'ak-47.jpg',
			'price' => 415,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:86']],
			'quality' => 0,
		],
		[
			'name' => 'auto-amnesia-haze-stuff',
			'image' => 'auto-amnesia-haze.jpg',
			'price' => 544,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:91']],
			'quality' => 0,
		],
		[
			'name' => 'amnesia-haze-stuff',
			'image' => 'amnesia-haze.jpg',
			'price' => 682,
			'weight' => 1,
			'premium' => 0,
			'properties' => ['requires' => ['~plantator:95']],
			'quality' => 0,
		],
	],
];
?>