<?php

return [
	'car-showroom' => [
		'city-car' => 1,
		'racing-car' => 1,
		'limousine' => 1,
	],
	'grocery-store' => [
		'loaf' => 10,
		'doughnut' => 7,
		'dinner' => 5,
		'kebab' => 3,
		'pizza' => 1,
		'water' => 10,
		'juice' => 7,
		'tea' => 5,
		'coffee' => 3,
		'energy-drink' => 1,
	],
	'grow-shop' => [
		'critical-seed' => 10,
		'shaman-seed' => 10,
		'grapefruit-seed' => 10,
		'passion-seed' => 10,
		'maroc-seed' => 10,
		'skunk-seed' => 10,
	],
	'gun-shop' => [
		'colt-1911' => 1,
		'glock' => 1,
		'ak-47' => 1,
		'm4a1' => 1,
		'bazooka' => 1,
		'flare' => 1,
		'bulletprof-vest' => 1,
		'kevlar' => 1,
	],
	'miscellaneous-store' => [
		'knife' => 1,
		'paralizator' => 1,
		'peper-spray' => 1,
		'knuckle-duster' => 1,
		'machete' => 1,
		'sword' => 1,
		'flare' => 1,
		'pan-colander' => 1,
		'squire-armor' => 1,
		'knight-armor' => 1,
		'samurai-armor' => 1,
	],
	'motorcycle-shop' => [
		'scooter' => 1,
		'quad' => 1,
		'cross' => 1,
		'motor' => 1,
		'chaser' => 1,
	],
	'sport-shop' => [
		'bicycle' => 1,
		'baseball-bat' => 1,
		't-shirt' => 1,
		'sumo-costume' => 1,
		'water' => 5,
		'energy-drink' => 3,
	],
	'toy-store' => [
		'stick' => 1,
		'foam-sword' => 1,
		'water-gun' => 1,
		'sumo-costume' => 1,
		'bicycle' => 1,
		'staff' => 1,
	],
];
?>